### ISSUE TITLE
Writing of last instruction word is incomplete

### ISSUE THREAD

**Issue by cpldcpu** [free-pdk/easy-pdk-programmer-software#11]
I came across a very interesting bug. It appears that the last instruction word is not completely written to the flash. See screenshot below showing a disassembly of the hex file before writing (right side) and after reading back from the device (PFS154, left side).

In this case a "ret" instruction is encoded here. Usually, when the source is only one file and the main loop never finished, this RET is never reached. However, when linking more than one source file, SDCC puts all subroutines from sources other than the main there, so that the missing RET will cause the MCU to enter a neverending loop.

![bug](https://user-images.githubusercontent.com/4086406/64077041-4ab0b480-cccc-11e9-8917-b0501ebff3db.PNG)

**Comment by freepdk** [comment]
Hi,

Unfortunately it never happened to me. More information is needed.

Please provide a sample IHEX file and the exact easypdkprog commands you use to reproduce (WRITE , READ, ...)

**Comment by cpldcpu** [comment]
Full example project attached. You can find the intel hex in "example/pfs1_xxx_blinky/main.ihx". It's a blinky on PA4. It does not work unless I create a dummy function at the end of the program as shown in "include/delay.c".

An exampe of a memory dump read back from the device is in "example/pfs1_xxx_blinky/out.bin". You can see that the last byte is 0x3f instead of 0x00.

The instructions used for programming are those from the makefile.
	$(PROGRAMMER) -n $(MCU) write $(TARGET)

[Toolchain.zip](https://github.com/free-pdk/easy-pdk-programmer-software/files/3564668/Toolchain.zip)

**Comment by freepdk** [comment]
Thanks for the files... same happens here. Strange that I never saw this before.

Fixed in commit 7778a53e8ca460d33e9893f70c1100116e6dfcaa

**Comment by cpldcpu** [comment]
Thank you for quick fixing! Will you generate a new release/exe?

**Comment by freepdk** [comment]
I added a new development tag, so auto build will create a new release anytime soon.
