### ISSUE TITLE
I'd be interesting to see this added to PlatformIO as a platform.

### ISSUE THREAD

**Issue by Duckle29** [free-pdk/easy-pdk-programmer-software#20]
**Is your feature request related to a problem? Please describe.**
I was watching Daves video setting up the whole free-pdk toolchain, and while it seemed fairly trivial compared to what other toolchains can be like, I do see why Dave ran into the issues he did. 

**Describe the solution you'd like**
It looks to my fairly untrained eye like all the bits and pieces are there to add support for this in platform IO, depending on how interested the platformIO team is, but I can't see why they'd deny the value of _such a low cost_ mcu family being made easily available to the masses.

Thanks for your time on this, it's very exciting :)

**Comment by freepdk** [comment]
This is the project for the open source programmer software only.

Since then a lot of new contributors got involved and you find more and more information on the https://free-pdk.github.io/ website.
