### ISSUE TITLE
DFU suffix signature

### ISSUE THREAD

**Issue by spth** [free-pdk/easy-pdk-programmer-software#4]
It seems the firmware file does not have a valid DFU suffix signature.
Current versions of dfu-utils warn about that, but it will be an error in future versions. So to ensure that nothing breaks in he future, it would be good if the build process would result in firmware with a valid DFU suffix signature.

**Comment by freepdk** [comment]
This is something I had on my list. Unfortunately I was not able to find an easy solution for this.

Most other people projects just ignore the warning for now...

**Comment by freepdk** [comment]
fixed in 4ca6f0ca92e9326f4aa57f6b3be9aadb7d075ae1
