### ISSUE TITLE
Output information about programmer hardware

### ISSUE THREAD

**Issue by cpldcpu** [free-pdk/easy-pdk-programmer-software#48]
**Is your feature request related to a problem? Please describe.**
Right now the information encoded in `_hw_variant` is not used anywhere.

**Describe the solution you'd like**
I would suggest to output this information when using the command line tool, for example as part of the "-v" or "-V" reply. 

Or any other idea how to use it?

**Comment by freepdk** [comment]
Hardware variant is used in the firmware to use different ADC channels already.

Till now there is no need to forward this information to host software at the moment. Ideally it should not matter for the host software what hardware variant is used at all.

**Comment by freepdk** [comment]
easypdkprog shows HwVariant and HwMod when executed with "-v".
