### ISSUE TITLE
Shield padauk programmer bluepill 

### ISSUE THREAD

**Issue by EDU-BR-TAR** [free-pdk/easy-pdk-programmer-software#59]
Hello, I would like to make a programmer shield for the bluepill board I believe that many have this MCU in their hands and it would make the programmer project even cheaper, could someone compile and provide the firmware for the stm32f103c8t6 please

**Comment by Vanbatai123** [comment]
i read some comment and it said that stm32f103 don't have dac so it cant use for this programmer.
