### ISSUE TITLE
PMS150G now supports maximum clock 8MHz

### ISSUE THREAD

**Issue by hashuser** [free-pdk/easy-pdk-programmer-software#64]
Padauk released version 0.05 of the PMS150G datasheet in 2021/12/16.
PMS150G now supports maximum clock 8MHz.

<img width="584" alt="Screenshot 2022-08-20 071558" src="https://user-images.githubusercontent.com/60065064/185731833-164ecfa4-405b-4784-bd65-a8385157969b.png">

<img width="568" alt="Screenshot 2022-08-20 070649" src="https://user-images.githubusercontent.com/60065064/185731796-50e272a3-a8b8-43cd-b90f-60ad69b1fac8.png">

**Comment by freepdk** [comment]
added the macros to the easypdk sample code header, see 07ec522
